const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEMS_FROM_CART: 'REMOVE_ITEMS_FROM_CART',
};

export default CartActionTypes;
